[package]
name = "round-based"
version = "0.2.0"
edition = "2021"
license = "GPL-3.0"
description = "Driver for MPC protocols"
repository = "https://github.com/ZenGo-X/round-based-protocol"
categories = ["asynchronous", "cryptography", "network-programming"]
keywords = ["round-based", "mpc", "protocol"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
phantom-type = "0.3"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
bincode = "1"
pin-project-lite = "0.2"
async-stream = "0.3"
tokio-stream = { version = "0.1", features = ["sync"] }
round-based-derive = { path = "../round-based-derive", optional = true }
thiserror = "1"

delivery-core = { path = "../delivery/core" }

# tls support
rustls = { version = "0.19", features = ["dangerous_configuration"], optional = true }
webpki = { version = "0.21", optional = true }
tokio-rustls = { version = "0.22", optional = true }

# trusted delivery support
sha2 = { version = "0.9", optional = true }
secp256k1 = { version = "0.20", features = ["global-context"], optional = true }
never = { version = "0.1", optional = true }
generic-array = { version = "0.14", optional = true }
aes-gcm = { version = "0.9", optional = true }
rand = { version = "0.8", optional = true }
serde_bytes = { version = "0.11", optional = true }
aead = { version = "0.4", optional = true }
hkdf = { version = "0.11", optional = true }
hex = { version = "0.4", optional = true, default-features = false }

# unstable features
rcgen = { version = "0.8", optional = true }

[dev-dependencies]
rand = "0.8"
rand_chacha = "0.3"
sha2 = "0.9"
hex = "*"
trybuild = "1"
rcgen = "0.8"
test-case = { version = "1", features = ["hamcrest_assertions"] }
hamcrest2 = "0.3"
proptest = "1"

[features]
default = ["tls"]
derive = ["round-based-derive"]
tls = ["rustls", "webpki", "tokio-rustls"]
trusted-delivery = ["tls", "secp256k1", "secp256k1/serde", "sha2", "never", "generic-array", "aes-gcm", "rand", "serde_bytes", "aead", "hkdf", "hex"]
unstable = ["rcgen"]

[[example]]
name = "mpc_random_generation"
required-features = ["derive"]

[[test]]
name = "derive"
required-features = ["derive"]
